// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shipservice.proto

package de.opensourcepress.shipservice;

public final class Shipservice {
  private Shipservice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ShipType
      implements com.google.protobuf.ProtocolMessageEnum {
    KREUZFAHRTSCHIFF(0, 1),
    CONTAINERSCHIFF(1, 2),
    TANKSCHIFF(2, 3),
    OTHER(3, 4),
    ;
    
    public static final int KREUZFAHRTSCHIFF_VALUE = 1;
    public static final int CONTAINERSCHIFF_VALUE = 2;
    public static final int TANKSCHIFF_VALUE = 3;
    public static final int OTHER_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static ShipType valueOf(int value) {
      switch (value) {
        case 1: return KREUZFAHRTSCHIFF;
        case 2: return CONTAINERSCHIFF;
        case 3: return TANKSCHIFF;
        case 4: return OTHER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ShipType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ShipType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ShipType>() {
            public ShipType findValueByNumber(int number) {
              return ShipType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.opensourcepress.shipservice.Shipservice.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ShipType[] VALUES = {
      KREUZFAHRTSCHIFF, CONTAINERSCHIFF, TANKSCHIFF, OTHER, 
    };
    
    public static ShipType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ShipType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:de.opensourcepress.shipservice.ShipType)
  }
  
  public interface ShipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required .de.opensourcepress.shipservice.ShipType type = 3;
    boolean hasType();
    de.opensourcepress.shipservice.Shipservice.ShipType getType();
  }
  public static final class Ship extends
      com.google.protobuf.GeneratedMessage
      implements ShipOrBuilder {
    // Use Ship.newBuilder() to construct.
    private Ship(Builder builder) {
      super(builder);
    }
    private Ship(boolean noInit) {}
    
    private static final Ship defaultInstance;
    public static Ship getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ship getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_Ship_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_Ship_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .de.opensourcepress.shipservice.ShipType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private de.opensourcepress.shipservice.Shipservice.ShipType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public de.opensourcepress.shipservice.Shipservice.ShipType getType() {
      return type_;
    }
    
    private void initFields() {
      id_ = 0;
      name_ = "";
      type_ = de.opensourcepress.shipservice.Shipservice.ShipType.KREUZFAHRTSCHIFF;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.Ship parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.opensourcepress.shipservice.Shipservice.Ship prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.opensourcepress.shipservice.Shipservice.ShipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_Ship_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_Ship_fieldAccessorTable;
      }
      
      // Construct using de.opensourcepress.shipservice.Shipservice.Ship.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = de.opensourcepress.shipservice.Shipservice.ShipType.KREUZFAHRTSCHIFF;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.opensourcepress.shipservice.Shipservice.Ship.getDescriptor();
      }
      
      public de.opensourcepress.shipservice.Shipservice.Ship getDefaultInstanceForType() {
        return de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance();
      }
      
      public de.opensourcepress.shipservice.Shipservice.Ship build() {
        de.opensourcepress.shipservice.Shipservice.Ship result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.opensourcepress.shipservice.Shipservice.Ship buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.opensourcepress.shipservice.Shipservice.Ship result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.opensourcepress.shipservice.Shipservice.Ship buildPartial() {
        de.opensourcepress.shipservice.Shipservice.Ship result = new de.opensourcepress.shipservice.Shipservice.Ship(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.opensourcepress.shipservice.Shipservice.Ship) {
          return mergeFrom((de.opensourcepress.shipservice.Shipservice.Ship)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.opensourcepress.shipservice.Shipservice.Ship other) {
        if (other == de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              de.opensourcepress.shipservice.Shipservice.ShipType value = de.opensourcepress.shipservice.Shipservice.ShipType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required .de.opensourcepress.shipservice.ShipType type = 3;
      private de.opensourcepress.shipservice.Shipservice.ShipType type_ = de.opensourcepress.shipservice.Shipservice.ShipType.KREUZFAHRTSCHIFF;
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public de.opensourcepress.shipservice.Shipservice.ShipType getType() {
        return type_;
      }
      public Builder setType(de.opensourcepress.shipservice.Shipservice.ShipType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = de.opensourcepress.shipservice.Shipservice.ShipType.KREUZFAHRTSCHIFF;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.opensourcepress.shipservice.Ship)
    }
    
    static {
      defaultInstance = new Ship(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.opensourcepress.shipservice.Ship)
  }
  
  public interface ShipRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string name = 1;
    java.util.List<String> getNameList();
    int getNameCount();
    String getName(int index);
  }
  public static final class ShipRequest extends
      com.google.protobuf.GeneratedMessage
      implements ShipRequestOrBuilder {
    // Use ShipRequest.newBuilder() to construct.
    private ShipRequest(Builder builder) {
      super(builder);
    }
    private ShipRequest(boolean noInit) {}
    
    private static final ShipRequest defaultInstance;
    public static ShipRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ShipRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipRequest_fieldAccessorTable;
    }
    
    // repeated string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList name_;
    public java.util.List<String>
        getNameList() {
      return name_;
    }
    public int getNameCount() {
      return name_.size();
    }
    public String getName(int index) {
      return name_.get(index);
    }
    
    private void initFields() {
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < name_.size(); i++) {
        output.writeBytes(1, name_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(name_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.opensourcepress.shipservice.Shipservice.ShipRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.opensourcepress.shipservice.Shipservice.ShipRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipRequest_fieldAccessorTable;
      }
      
      // Construct using de.opensourcepress.shipservice.Shipservice.ShipRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.opensourcepress.shipservice.Shipservice.ShipRequest.getDescriptor();
      }
      
      public de.opensourcepress.shipservice.Shipservice.ShipRequest getDefaultInstanceForType() {
        return de.opensourcepress.shipservice.Shipservice.ShipRequest.getDefaultInstance();
      }
      
      public de.opensourcepress.shipservice.Shipservice.ShipRequest build() {
        de.opensourcepress.shipservice.Shipservice.ShipRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.opensourcepress.shipservice.Shipservice.ShipRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.opensourcepress.shipservice.Shipservice.ShipRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.opensourcepress.shipservice.Shipservice.ShipRequest buildPartial() {
        de.opensourcepress.shipservice.Shipservice.ShipRequest result = new de.opensourcepress.shipservice.Shipservice.ShipRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = new com.google.protobuf.UnmodifiableLazyStringList(
              name_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.name_ = name_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.opensourcepress.shipservice.Shipservice.ShipRequest) {
          return mergeFrom((de.opensourcepress.shipservice.Shipservice.ShipRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.opensourcepress.shipservice.Shipservice.ShipRequest other) {
        if (other == de.opensourcepress.shipservice.Shipservice.ShipRequest.getDefaultInstance()) return this;
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureNameIsMutable();
              name_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string name = 1;
      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getNameList() {
        return java.util.Collections.unmodifiableList(name_);
      }
      public int getNameCount() {
        return name_.size();
      }
      public String getName(int index) {
        return name_.get(index);
      }
      public Builder setName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllName(
          java.lang.Iterable<String> values) {
        ensureNameIsMutable();
        super.addAll(values, name_);
        onChanged();
        return this;
      }
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addName(com.google.protobuf.ByteString value) {
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:de.opensourcepress.shipservice.ShipRequest)
    }
    
    static {
      defaultInstance = new ShipRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.opensourcepress.shipservice.ShipRequest)
  }
  
  public interface ShipResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .de.opensourcepress.shipservice.ShipResponse.ShipItem results = 1;
    java.util.List<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem> 
        getResultsList();
    de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem getResults(int index);
    int getResultsCount();
    java.util.List<? extends de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder> 
        getResultsOrBuilderList();
    de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder getResultsOrBuilder(
        int index);
  }
  public static final class ShipResponse extends
      com.google.protobuf.GeneratedMessage
      implements ShipResponseOrBuilder {
    // Use ShipResponse.newBuilder() to construct.
    private ShipResponse(Builder builder) {
      super(builder);
    }
    private ShipResponse(boolean noInit) {}
    
    private static final ShipResponse defaultInstance;
    public static ShipResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ShipResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_fieldAccessorTable;
    }
    
    public interface ShipItemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required .de.opensourcepress.shipservice.Ship ship = 1;
      boolean hasShip();
      de.opensourcepress.shipservice.Shipservice.Ship getShip();
      de.opensourcepress.shipservice.Shipservice.ShipOrBuilder getShipOrBuilder();
    }
    public static final class ShipItem extends
        com.google.protobuf.GeneratedMessage
        implements ShipItemOrBuilder {
      // Use ShipItem.newBuilder() to construct.
      private ShipItem(Builder builder) {
        super(builder);
      }
      private ShipItem(boolean noInit) {}
      
      private static final ShipItem defaultInstance;
      public static ShipItem getDefaultInstance() {
        return defaultInstance;
      }
      
      public ShipItem getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required .de.opensourcepress.shipservice.Ship ship = 1;
      public static final int SHIP_FIELD_NUMBER = 1;
      private de.opensourcepress.shipservice.Shipservice.Ship ship_;
      public boolean hasShip() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public de.opensourcepress.shipservice.Shipservice.Ship getShip() {
        return ship_;
      }
      public de.opensourcepress.shipservice.Shipservice.ShipOrBuilder getShipOrBuilder() {
        return ship_;
      }
      
      private void initFields() {
        ship_ = de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasShip()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getShip().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, ship_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, ship_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_fieldAccessorTable;
        }
        
        // Construct using de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getShipFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (shipBuilder_ == null) {
            ship_ = de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance();
          } else {
            shipBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.getDescriptor();
        }
        
        public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem getDefaultInstanceForType() {
          return de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.getDefaultInstance();
        }
        
        public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem build() {
          de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem buildPartial() {
          de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem result = new de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (shipBuilder_ == null) {
            result.ship_ = ship_;
          } else {
            result.ship_ = shipBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem) {
            return mergeFrom((de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem other) {
          if (other == de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.getDefaultInstance()) return this;
          if (other.hasShip()) {
            mergeShip(other.getShip());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasShip()) {
            
            return false;
          }
          if (!getShip().isInitialized()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                de.opensourcepress.shipservice.Shipservice.Ship.Builder subBuilder = de.opensourcepress.shipservice.Shipservice.Ship.newBuilder();
                if (hasShip()) {
                  subBuilder.mergeFrom(getShip());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setShip(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .de.opensourcepress.shipservice.Ship ship = 1;
        private de.opensourcepress.shipservice.Shipservice.Ship ship_ = de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            de.opensourcepress.shipservice.Shipservice.Ship, de.opensourcepress.shipservice.Shipservice.Ship.Builder, de.opensourcepress.shipservice.Shipservice.ShipOrBuilder> shipBuilder_;
        public boolean hasShip() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public de.opensourcepress.shipservice.Shipservice.Ship getShip() {
          if (shipBuilder_ == null) {
            return ship_;
          } else {
            return shipBuilder_.getMessage();
          }
        }
        public Builder setShip(de.opensourcepress.shipservice.Shipservice.Ship value) {
          if (shipBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ship_ = value;
            onChanged();
          } else {
            shipBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder setShip(
            de.opensourcepress.shipservice.Shipservice.Ship.Builder builderForValue) {
          if (shipBuilder_ == null) {
            ship_ = builderForValue.build();
            onChanged();
          } else {
            shipBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder mergeShip(de.opensourcepress.shipservice.Shipservice.Ship value) {
          if (shipBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                ship_ != de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance()) {
              ship_ =
                de.opensourcepress.shipservice.Shipservice.Ship.newBuilder(ship_).mergeFrom(value).buildPartial();
            } else {
              ship_ = value;
            }
            onChanged();
          } else {
            shipBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder clearShip() {
          if (shipBuilder_ == null) {
            ship_ = de.opensourcepress.shipservice.Shipservice.Ship.getDefaultInstance();
            onChanged();
          } else {
            shipBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        public de.opensourcepress.shipservice.Shipservice.Ship.Builder getShipBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getShipFieldBuilder().getBuilder();
        }
        public de.opensourcepress.shipservice.Shipservice.ShipOrBuilder getShipOrBuilder() {
          if (shipBuilder_ != null) {
            return shipBuilder_.getMessageOrBuilder();
          } else {
            return ship_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            de.opensourcepress.shipservice.Shipservice.Ship, de.opensourcepress.shipservice.Shipservice.Ship.Builder, de.opensourcepress.shipservice.Shipservice.ShipOrBuilder> 
            getShipFieldBuilder() {
          if (shipBuilder_ == null) {
            shipBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                de.opensourcepress.shipservice.Shipservice.Ship, de.opensourcepress.shipservice.Shipservice.Ship.Builder, de.opensourcepress.shipservice.Shipservice.ShipOrBuilder>(
                    ship_,
                    getParentForChildren(),
                    isClean());
            ship_ = null;
          }
          return shipBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:de.opensourcepress.shipservice.ShipResponse.ShipItem)
      }
      
      static {
        defaultInstance = new ShipItem(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:de.opensourcepress.shipservice.ShipResponse.ShipItem)
    }
    
    // repeated .de.opensourcepress.shipservice.ShipResponse.ShipItem results = 1;
    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem> results_;
    public java.util.List<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem> getResultsList() {
      return results_;
    }
    public java.util.List<? extends de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    public int getResultsCount() {
      return results_.size();
    }
    public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem getResults(int index) {
      return results_.get(index);
    }
    public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }
    
    private void initFields() {
      results_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getResultsCount(); i++) {
        if (!getResults(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(1, results_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.opensourcepress.shipservice.Shipservice.ShipResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.opensourcepress.shipservice.Shipservice.ShipResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.opensourcepress.shipservice.Shipservice.ShipResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.opensourcepress.shipservice.Shipservice.internal_static_de_opensourcepress_shipservice_ShipResponse_fieldAccessorTable;
      }
      
      // Construct using de.opensourcepress.shipservice.Shipservice.ShipResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.opensourcepress.shipservice.Shipservice.ShipResponse.getDescriptor();
      }
      
      public de.opensourcepress.shipservice.Shipservice.ShipResponse getDefaultInstanceForType() {
        return de.opensourcepress.shipservice.Shipservice.ShipResponse.getDefaultInstance();
      }
      
      public de.opensourcepress.shipservice.Shipservice.ShipResponse build() {
        de.opensourcepress.shipservice.Shipservice.ShipResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.opensourcepress.shipservice.Shipservice.ShipResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.opensourcepress.shipservice.Shipservice.ShipResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.opensourcepress.shipservice.Shipservice.ShipResponse buildPartial() {
        de.opensourcepress.shipservice.Shipservice.ShipResponse result = new de.opensourcepress.shipservice.Shipservice.ShipResponse(this);
        int from_bitField0_ = bitField0_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.opensourcepress.shipservice.Shipservice.ShipResponse) {
          return mergeFrom((de.opensourcepress.shipservice.Shipservice.ShipResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.opensourcepress.shipservice.Shipservice.ShipResponse other) {
        if (other == de.opensourcepress.shipservice.Shipservice.ShipResponse.getDefaultInstance()) return this;
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getResultsCount(); i++) {
          if (!getResults(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder subBuilder = de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResults(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .de.opensourcepress.shipservice.ShipResponse.ShipItem results = 1;
      private java.util.List<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = new java.util.ArrayList<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem>(results_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder> resultsBuilder_;
      
      public java.util.List<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      public Builder setResults(
          int index, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setResults(
          int index, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addResults(de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addResults(
          int index, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addResults(
          de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addResults(
          int index, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllResults(
          java.lang.Iterable<? extends de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          super.addAll(values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder> 
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.getDefaultInstance());
      }
      public de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.getDefaultInstance());
      }
      public java.util.List<de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder> 
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder> 
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder, de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItemOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:de.opensourcepress.shipservice.ShipResponse)
    }
    
    static {
      defaultInstance = new ShipResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.opensourcepress.shipservice.ShipResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_opensourcepress_shipservice_Ship_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_opensourcepress_shipservice_Ship_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_opensourcepress_shipservice_ShipRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_opensourcepress_shipservice_ShipRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_opensourcepress_shipservice_ShipResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_opensourcepress_shipservice_ShipResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021shipservice.proto\022\036de.opensourcepress." +
      "shipservice\"X\n\004Ship\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030" +
      "\002 \002(\t\0226\n\004type\030\003 \002(\0162(.de.opensourcepress" +
      ".shipservice.ShipType\"\033\n\013ShipRequest\022\014\n\004" +
      "name\030\001 \003(\t\"\226\001\n\014ShipResponse\022F\n\007results\030\001" +
      " \003(\01325.de.opensourcepress.shipservice.Sh" +
      "ipResponse.ShipItem\032>\n\010ShipItem\0222\n\004ship\030" +
      "\001 \002(\0132$.de.opensourcepress.shipservice.S" +
      "hip*P\n\010ShipType\022\024\n\020KREUZFAHRTSCHIFF\020\001\022\023\n" +
      "\017CONTAINERSCHIFF\020\002\022\016\n\nTANKSCHIFF\020\003\022\t\n\005OT",
      "HER\020\0042s\n\013ShipService\022d\n\007getShip\022+.de.ope" +
      "nsourcepress.shipservice.ShipRequest\032,.d" +
      "e.opensourcepress.shipservice.ShipRespon" +
      "se"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_opensourcepress_shipservice_Ship_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_opensourcepress_shipservice_Ship_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_opensourcepress_shipservice_Ship_descriptor,
              new java.lang.String[] { "Id", "Name", "Type", },
              de.opensourcepress.shipservice.Shipservice.Ship.class,
              de.opensourcepress.shipservice.Shipservice.Ship.Builder.class);
          internal_static_de_opensourcepress_shipservice_ShipRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_opensourcepress_shipservice_ShipRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_opensourcepress_shipservice_ShipRequest_descriptor,
              new java.lang.String[] { "Name", },
              de.opensourcepress.shipservice.Shipservice.ShipRequest.class,
              de.opensourcepress.shipservice.Shipservice.ShipRequest.Builder.class);
          internal_static_de_opensourcepress_shipservice_ShipResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_de_opensourcepress_shipservice_ShipResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_opensourcepress_shipservice_ShipResponse_descriptor,
              new java.lang.String[] { "Results", },
              de.opensourcepress.shipservice.Shipservice.ShipResponse.class,
              de.opensourcepress.shipservice.Shipservice.ShipResponse.Builder.class);
          internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_descriptor =
            internal_static_de_opensourcepress_shipservice_ShipResponse_descriptor.getNestedTypes().get(0);
          internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_opensourcepress_shipservice_ShipResponse_ShipItem_descriptor,
              new java.lang.String[] { "Ship", },
              de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.class,
              de.opensourcepress.shipservice.Shipservice.ShipResponse.ShipItem.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
